### ISSUE TITLE
[Feature request] Dropdown to select role in administration page

### ISSUE THREAD

**Issue by hgvo9** [safely-app/Front-End-Web#9]
When I'm in the 'Administration' page and would like to change the role of a user, I have to specify by typing the role in a textinput, wouldn't it be better if it was a dropdown where I can choose among the existing role ?

Today, I can type whatever role I want and can edit it :

![image](https://user-images.githubusercontent.com/62654884/120691680-0a84f400-c4a7-11eb-95e8-b09003569da3.png)

@Trushy @Iboakg5745 What happens in the back-end if the user has an unknown role ?

**Comment by louischristner** [comment]
I created a pull request for the dropdown, feel free to check it.

**Comment by hgvo9** [comment]
New feature added in pull request #13 by @louischristner, I'll be closing this feature request
